FROM python:3.9.10

WORKDIR /app

ARG VK_AUTH_TOKEN
ARG VK_AUTH_TOKEN_KATE
ARG VK_AUTH_AGENT
ARG SPOTIFY_CLIENT_ID
ARG SPOTIFY_CLIENT_SECRET
ARG TELEGRAM_BOT_TOKEN

ENV VK_AUTH_TOKEN=$VK_AUTH_TOKEN
ENV VK_AUTH_TOKEN_KATE=$VK_AUTH_TOKEN_KATE
ENV VK_AUTH_AGENT=$VK_AUTH_AGENT
ENV SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID
ENV SPOTIFY_CLIENT_SECRET=$SPOTIFY_CLIENT_SECRET
ENV TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN

COPY requirements.txt ./
RUN pip install -r requirements.txt && apt-get update

COPY *.py ./
COPY platforms ./platforms

COPY run.sh run.sh
CMD ./run.sh
